name: reusable 
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: name of artifact
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: show files
        run: ls
      - name: deploying
        run: echo "Deploying...."