name: reusable 
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: name of artifact
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: echo "Deploying...."